// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9isw2RX3VexnIcTQt2ofvJf3Ujg0Jwg',
    appId: '1:906419232621:web:4ab4e0e0bc752d3f900464',
    messagingSenderId: '906419232621',
    projectId: 'final-project-flutter-bb9e1',
    authDomain: 'final-project-flutter-bb9e1.firebaseapp.com',
    storageBucket: 'final-project-flutter-bb9e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCBW_uJeh5xZ2IexV-ShVufzLU0Zx8dgQ',
    appId: '1:906419232621:android:db406699c78b164c900464',
    messagingSenderId: '906419232621',
    projectId: 'final-project-flutter-bb9e1',
    storageBucket: 'final-project-flutter-bb9e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzX4FerQiDo9Dv9iXLE2yeUnmFJK57aQ',
    appId: '1:906419232621:ios:c1ceee839e14f31c900464',
    messagingSenderId: '906419232621',
    projectId: 'final-project-flutter-bb9e1',
    storageBucket: 'final-project-flutter-bb9e1.appspot.com',
    iosBundleId: 'com.example.finalProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzX4FerQiDo9Dv9iXLE2yeUnmFJK57aQ',
    appId: '1:906419232621:ios:c1ceee839e14f31c900464',
    messagingSenderId: '906419232621',
    projectId: 'final-project-flutter-bb9e1',
    storageBucket: 'final-project-flutter-bb9e1.appspot.com',
    iosBundleId: 'com.example.finalProjectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-9isw2RX3VexnIcTQt2ofvJf3Ujg0Jwg',
    appId: '1:906419232621:web:ff31272825287286900464',
    messagingSenderId: '906419232621',
    projectId: 'final-project-flutter-bb9e1',
    authDomain: 'final-project-flutter-bb9e1.firebaseapp.com',
    storageBucket: 'final-project-flutter-bb9e1.appspot.com',
  );
}
